### ISSUE TITLE
Turtle turn-balancing

### ISSUE THREAD

**Issue by berleant** [bantamtools/FluidNC#18]
Description: DD option to try to balance left and right turns as a band-aid for angle error accumulation

## From Pivotal Tracker:
ID 186064283 
URL https://www.pivotaltracker.com/story/show/186064283 
Estimate 2
Created on Sep 18, 2023 
Deadline  
Requested by Devin Cooper

**Comment by BenElgin** [comment]
This functionality was completed, but proved insufficient at reducing error accumulation
